from .checkcast import *
from .getfield import *
from .getstatic import *
from .instanceof import *
from .invokespecial import *
from .invokevirtual import *
from .invokestatic import *
from .invokeinterface import *
from .new import *
from .putfield import *
from .putstatic import *
from .newarray import *
from .anewarray import *
from .arraylength import *
from .multianewarray import *
from .athrow import *